import Nav from "./components/Nav";
import type { Metadata } from "next";
import BottomTabs from "./components/BottomTabs";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         className="font-sans antialiased"
      >
      <Nav />
        {children}

</body>
    </html>
  );
}





